spring:
  # 数据库相关
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ylyun_backup?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名

